### PR TITLE
Updating license check algorithm

### PR DESCRIPTION
**Pull request by alexalikiotis**
This PR fixes the following issue:

The license-checker module gives back some license names with a * at the end (e.x "MIT*") which means that the module deduced the license from something different than the LICENSE.md file.

The current license check "algorithm" (which it's just an equality check `===`) misses these responses because "MIT" !== "MIT*".

This update of the license check "algorithm" uses the `.includes` javascript method (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) so we can also catch these scenarios.

It can also solve the case of "(Apache-2.0 OR MIT)" (because in rare cases a module is under 2 licenses)

### CODE REVIEW

**Comment by helio-frota** [comment]
> The license-checker module gives back some license names with a * at the end (e.x "MIT*") which means that the module deduced the license from something different than the LICENSE.md file.

That is interesting.

I really don't remember that part in license-reporter. 
Not sure if that case were covered.

**Review by helio-frota — APPROVED** [review]

**Comment by richardlau** [comment]
Won't using `includes` match `GPL` in `AGPL` (which are not the same licenses)?

**Comment by alexalikiotis** [comment]
@richardlau Hmmm you're right. GPL will match AGPL when using `includes` 😑

**Comment by helio-frota** [comment]
@richardlau good catch!

**Comment by alexalikiotis** [comment]
The only other option is to handle the `*` case separately and for the `(Apache-2.0 OR MIT)` case split the string to substrings (based on the OR keyword) and use the `===` for the equality check.

**Comment by alexalikiotis** [comment]
Or maybe we can use a smart regex ?? 🤔

**Comment by helio-frota** [comment]
@alexalikiotis That approach you mentioned is valid to me to handle the cases separately.

But it is natural to raise some questions:

Something has changed in the license-checker?
Makes sense for us to review their changelog?

Maybe we should have unit tests to cover each situation for safety (in case changes in license-checker also)

**Comment by richardlau** [comment]
> Or maybe we can use a smart regex ?? 🤔

Yeah, that would be my suggestion. Pass `name` through a regexp escaping function like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping and then surround it by word boundary, e.g. 
```
new RegexExp(`\\b${escapeRegExp(name)}\\b`)
```

**Comment by alexalikiotis** [comment]
@helio-frota @richardlau I updated the license check "algorithm" to use a `regex` instead of `.includes`. Also, I added some tests about it.

**Review by richardlau — APPROVED** [review]

**Review by helio-frota — APPROVED** [review]

**Pull request merged**
